<script src="<?php echo $base_url;?>/vendor/jquery/jquery.min.js"></script>
<script src="<?php echo $base_url;?>/vendor/popper.js/umd/popper.min.js"> </script>
<script src="<?php echo $base_url;?>/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $base_url;?>/vendor/jquery.cookie/jquery.cookie.js"> </script>
<script src="<?php echo $base_url;?>/vendor/waypoints/lib/jquery.waypoints.min.js"> </script>
<script src="<?php echo $base_url;?>/vendor/jquery.counterup/jquery.counterup.min.js"> </script>
<script src="<?php echo $base_url;?>/vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="<?php echo $base_url;?>/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js"></script>
<script src="<?php echo $base_url;?>/js/jquery.parallax-1.1.3.js"></script>
<script src="<?php echo $base_url;?>/vendor/bootstrap-select/js/bootstrap-select.min.js"></script>
<script src="<?php echo $base_url;?>/vendor/jquery.scrollto/jquery.scrollTo.min.js"></script>
<script src="<?php echo $base_url;?>/js/front.js"></script>
