<script src="<?php echo $base_url;?>/assets/jquery/jquery.min.js"></script>
<script src="<?php echo $base_url;?>/assets/popper.js/umd/popper.min.js"> </script>
<script src="<?php echo $base_url;?>/assets/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $base_url;?>/assets/jquery.cookie/jquery.cookie.js"> </script>
<script src="<?php echo $base_url;?>/assets/waypoints/lib/jquery.waypoints.min.js"> </script>
<script src="<?php echo $base_url;?>/assets/jquery.counterup/jquery.counterup.min.js"> </script>
<script src="<?php echo $base_url;?>/assets/owl.carousel/owl.carousel.min.js"></script>
<script src="<?php echo $base_url;?>/assets/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js"></script>
<script src="<?php echo $base_url;?>/assets/js/jquery.parallax-1.1.3.js"></script>
<script src="<?php echo $base_url;?>/assets/bootstrap-select/js/bootstrap-select.min.js"></script>
<script src="<?php echo $base_url;?>/assets/jquery.scrollto/jquery.scrollTo.min.js"></script>
<script src="<?php echo $base_url;?>/assets/js/front.js"></script>
